spring.application.name=twinsburger

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/TwinsBurgerBD
spring.datasource.username=postgres
spring.datasource.password=UDavid20